title: Advanced Programming Spring 2019
description: All resources will be published here.

# Jekyll settings
permalink:  none             # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: true          # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
style: default               # choose between "default", "contrast" and "minimal"
dark_theme: false            # enables dark mode

navigation:                  # (optional) site navigation in the header
  - index.md
  - pap.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  
queras:
  Hatami: https://quera.ir/course/2770/
  MostafaZade: https://quera.ir/course/2838/

plugins: 
 - jekyll-paginate
 - jekyll-default-layout

#custom variables

hw_paths:
  - hw2:
    - hatami: https://quera.ir/course/assignments/8026/problems
    - mostafa: https://quera.ir/course/assignments/8609/problems
    - pdf: /assets/homeworks/AP_HW2.pdf